
Traceback (most recent call last):
  File "XXX/COMP579_project/GROUPS/GROUP_013/agent.py", line 67, in load_weights
    pretrained_model = torch.load(pretrained_model_path)
  File "XXX/.conda/envs/COMP579_project/lib/python3.7/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "XXX/.conda/envs/COMP579_project/lib/python3.7/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "XXX/.conda/envs/COMP579_project/lib/python3.7/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'GROUP_MJ1/submitted_model.pth.tar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evaluate_agents.py", line 193, in <module>
    agent.load_weights(root_path=path) 
  File "XXX/COMP579_project/GROUPS/GROUP_013/agent.py", line 70, in load_weights
    \nE.g. python3 train_agent.py --group vpg_agent --load 2022-03-31_12h46m44/vpg_ckpt_98.888")
Exception: Invalid location for loading pretrained model. You need folder/filename in results folder (without .pth.tar).                 
E.g. python3 train_agent.py --group vpg_agent --load 2022-03-31_12h46m44/vpg_ckpt_98.888
